In [12]:
import pandas as pd

In [30]:
db = pd.read_parquet("/home/sergey/projects/Credit_scoring/raw/train_data/train_data_2.pq")
db[:5]

,id,rn,pre_since_opened,pre_since_confirmed,pre_pterm,pre_fterm,pre_till_pclose,pre_till_fclose,pre_loans_credit_limit,pre_loans_next_pay_summ,...,enc_paym_21,enc_paym_22,enc_paym_23,enc_paym_24,enc_loans_account_holder_type,enc_loans_credit_status,enc_loans_credit_type,enc_loans_account_cur,pclose_flag,fclose_flag
0,500000,1,13,4,8,11,13,3,18,6,...,3,3,3,4,1,3,4,1,0,0
1,500000,2,13,14,15,9,3,5,12,2,...,3,3,3,4,1,3,4,1,0,0
2,500000,3,18,5,13,2,5,10,6,2,...,3,3,3,4,1,3,1,1,0,0
3,500000,4,4,2,4,8,1,11,10,1,...,0,0,0,1,1,2,3,1,1,1
4,500000,5,5,16,0,8,14,11,3,2,...,0,0,0,1,1,2,3,1,0,1

In [20]:
db.shape

(2080508, 61)

In [24]:
db.describe().iloc[1:, :]

,id,rn,pre_since_opened,pre_since_confirmed,pre_pterm,pre_fterm,pre_till_pclose,pre_till_fclose,pre_loans_credit_limit,pre_loans_next_pay_summ,...,enc_paym_21,enc_paym_22,enc_paym_23,enc_paym_24,enc_loans_account_holder_type,enc_loans_credit_status,enc_loans_credit_type,enc_loans_account_cur,pclose_flag,fclose_flag
mean,624925.909198,6.793881,9.293492,8.439272,8.387317,8.247518,7.231118,8.394435,9.745270,2.380386,...,2.320920,2.350850,2.384512,3.538510,1.031622,2.686905,3.323721,1.001984,0.142172,0.240264
std,72361.930594,5.278811,5.744432,4.617817,5.320045,4.422861,5.164903,4.210547,5.812055,1.340782,...,1.242748,1.223176,1.199742,1.072883,0.293349,0.492269,1.093841,0.052849,0.349227,0.427244
min,500000.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,561941.000000,3.000000,5.000000,5.000000,4.000000,6.000000,2.000000,5.000000,5.000000,2.000000,...,3.000000,3.000000,3.000000,4.000000,1.000000,2.000000,3.000000,1.000000,0.000000,0.000000
50%,624948.500000,5.000000,9.000000,9.000000,8.000000,8.000000,7.000000,10.000000,10.000000,2.000000,...,3.000000,3.000000,3.000000,4.000000,1.000000,3.000000,4.000000,1.000000,0.000000,0.000000
75%,687615.000000,10.000000,14.000000,12.000000,14.000000,11.000000,12.000000,11.000000,15.000000,2.000000,...,3.000000,3.000000,3.000000,4.000000,1.000000,3.000000,4.000000,1.000000,0.000000,0.000000
max,749999.000000,51.000000,19.000000,17.000000,17.000000,16.000000,16.000000,15.000000,19.000000,6.000000,...,3.000000,3.000000,3.000000,4.000000,6.000000,6.000000,5.000000,3.000000,1.000000,1.000000

In [14]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2080508 entries, 0 to 2080507
Data columns (total 61 columns):
 #   Column                         Dtype
---  ------                         -----
 0   id                             int64
 1   rn                             int64
 2   pre_since_opened               int64
 3   pre_since_confirmed            int64
 4   pre_pterm                      int64
 5   pre_fterm                      int64
 6   pre_till_pclose                int64
 7   pre_till_fclose                int64
 8   pre_loans_credit_limit         int64
 9   pre_loans_next_pay_summ        int64
 10  pre_loans_outstanding          int64
 11  pre_loans_total_overdue        int64
 12  pre_loans_max_overdue_sum      int64
 13  pre_loans_credit_cost_rate     int64
 14  pre_loans5                     int64
 15  pre_loans530                   int64
 16  pre_loans3060                  int64
 17  pre_loans6090                  int64
 18  pre_loans90                    int64
 19  is_zero_loans5                 int64
 20  is_zero_loans530               int64
 21  is_zero_loans3060              int64
 22  is_zero_loans6090              int64
 23  is_zero_loans90                int64
 24  pre_util                       int64
 25  pre_over2limit                 int64
 26  pre_maxover2limit              int64
 27  is_zero_util                   int64
 28  is_zero_over2limit             int64
 29  is_zero_maxover2limit          int64
 30  enc_paym_0                     int64
 31  enc_paym_1                     int64
 32  enc_paym_2                     int64
 33  enc_paym_3                     int64
 34  enc_paym_4                     int64
 35  enc_paym_5                     int64
 36  enc_paym_6                     int64
 37  enc_paym_7                     int64
 38  enc_paym_8                     int64
 39  enc_paym_9                     int64
 40  enc_paym_10                    int64
 41  enc_paym_11                    int64
 42  enc_paym_12                    int64
 43  enc_paym_13                    int64
 44  enc_paym_14                    int64
 45  enc_paym_15                    int64
 46  enc_paym_16                    int64
 47  enc_paym_17                    int64
 48  enc_paym_18                    int64
 49  enc_paym_19                    int64
 50  enc_paym_20                    int64
 51  enc_paym_21                    int64
 52  enc_paym_22                    int64
 53  enc_paym_23                    int64
 54  enc_paym_24                    int64
 55  enc_loans_account_holder_type  int64
 56  enc_loans_credit_status        int64
 57  enc_loans_credit_type          int64
 58  enc_loans_account_cur          int64
 59  pclose_flag                    int64
 60  fclose_flag                    int64
dtypes: int64(61)
memory usage: 968.3 MB

In [36]:
db.isna().sum()

id                         0
rn                         0
pre_since_opened           0
pre_since_confirmed        0
pre_pterm                  0
                          ..
enc_loans_credit_status    0
enc_loans_credit_type      0
enc_loans_account_cur      0
pclose_flag                0
fclose_flag                0
Length: 61, dtype: int64